version: '3.9'
services:
  nginx:
    container_name: proxy
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/images:/srv/images               # Header images served by nginx
    restart: unless-stopped
  events:
    container_name: events
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse/events:latest
    expose:
      - 3000/tcp
    volumes:
      - /srv/images:/srv/images               # Header images served by nginx
    restart: unless-stopped
    environment:
      DATABASE_ENDPOINT: ${RDS_ENDPOINT}
      MYSQL_USER: ${RDS_USERNAME}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
  users:
    container_name: users
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse/users:latest
    expose:
      - 4000/tcp
    restart: unless-stopped
    environment:
      DATABASE_ENDPOINT: ${RDS_ENDPOINT}
      MYSQL_USER: ${RDS_USERNAME}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
  db:
    container_name: database
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${RDS_USERNAME}
      MYSQL_PASSWORD: ${RDS_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${RDS_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql