version: '3.9'
services:
  nginx:
    container_name: proxy
    build: ./packages/nginx/dev
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./build:/etc/nginx/data
      - ./.tmp:/srv/images
      - ./packages/nginx/dev:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.t
      - APP=${HOST_IP}:4443
      - EVENTS=events:3000
      - USERS=users:4000
    extra_hosts:
      - deltahouse.no:${HOST_IP}
      - api.deltahouse.no:${HOST_IP}
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./packages/database:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=nette
    depends_on:
      - db
  events:
    container_name: events
    build:
      context: ./packages/events
      dockerfile: Dockerfile.dev
    expose:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./packages/events/build:/usr/src/app  # Hot Reload
      - ./.tmp:/srv/images                    # Header Images -> /etc/nginx/images (in nginx container)
  users:
    container_name: users
    build: ./packages/users
    expose:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - ./packages/users/src:/usr/src/app  # Hot Reload
    command: npm run docker:hmr
  # mail:
  #   container_name: mail-server
  #   build: ./packages/mail
  #   expose:
  #     - 25:25
  #   extra_hosts:
  #     - mail.deltahouse.no:${HOST_IP}
  #     - deltahouse.no:${HOST_IP}