version: '3.9'
services:
  nginx:
    build: ./packages/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./build:/etc/nginx/data
      - ./packages/nginx/dev:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.t
      - HOST=${HOST_IP} # deltahouse.no
      - APP=${HOST_IP}:4443
      - EVENTS=events:3000
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./packages/database:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=nette
    depends_on:
      - db
  events:
    build: ./packages/events
    expose:
      - 3000:3000