version: '3.9'
services:
  nginx:
    container_name: proxy
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/images:/etc/nginx/images:ro    # Header images served by nginx
    # environment:
    #   - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.t
    #   - EVENTS=events:3000
    #   - USERS=users:4000
    # extra_hosts:
    #   - deltahouse.no:16.170.208.44
    #   - api.deltahouse.no:16.170.208.44
    restart: unless-stopped
  db:
    container_name: database
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passord
      MYSQL_ROOT_PASSWORD: passord      # TODO: Keep secrets safe
    ports:
      - 3306/tcp
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  events:
    container_name: events
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse/events:latest
    expose:
      - 3000/tcp
    volumes:
      - /srv/images:/srv/images              # Header images served by nginx
    restart: unless-stopped
  users:
    container_name: users
    image: 482961953931.dkr.ecr.eu-north-1.amazonaws.com/deltahouse/users:latest
    expose:
      - 4000/tcp
    restart: unless-stopped